name: f5c C/C++ CI MACOSX Github

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  os_x_10_15:
    name: OSX 10.15
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: brew install hdf5 autoconf automake
    - name: build
      run: autoreconf --install && ./configure && make -j8
    - name: test
      run: make test
  os_x_11:
    name: OSX 11
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: brew install hdf5 autoconf automake
    - name: build
      run: autoreconf --install  && ./configure && make -j8
    - name: test
      run: make test      
  os_x_10_15_make:
    name: OSX make
    runs-on: macos-10.15 
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: brew install gcc autoconf automake
    - name: build
      run: make
    - name: test
      run: make test
