name: f5c C/C++ CI Github

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  ubuntu_14_local_hts:
    name: ubuntu 14 local hts
    runs-on: ubuntu-16.04
    container: ubuntu:14.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libhdf5-dev gcc g++ autoconf automake make
    - name: env
      run: lsb_release -a &&  ldd --version && gcc --version && g++ --version
    - name: build
      run: autoreconf && ./scripts/install-hts.sh && ./configure && make -j8
    - name: test
      run: make test
