name: Linux ARM

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  ubuntu_arm:
    name: ubuntu arm
    runs-on: ubuntu-latest
    steps:
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: 'uname -a'
    - uses: actions/checkout@v1
    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: >
          bash -c "apt-get update &&
          apt-get install -y zlib1g-dev libhdf5-dev gcc g++ autoconf automake make wget &&
          ldd --version && gcc --version && g++ --version &&
          autoreconf &&
          ./scripts/install-hts.sh &&
          ./configure &&
          make -j8 &&
          make test"
