name: f5c C/C++ CI Linux x86_64 Github

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  ubuntu_14_local_hts:
    name: ubuntu 14 local hts
    runs-on: ubuntu-16.04
    container: ubuntu:14.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libhdf5-dev gcc g++ autoconf automake make wget
    - name: env
      run: lsb_release -a &&  ldd --version && gcc --version && g++ --version
    - name: build
      run: autoreconf && ./scripts/install-hts.sh && ./configure && make -j8
    - name: test
      run: make test
  ubuntu_16_install_scripts:
    name: Ubuntu 16 install scripts
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev valgrind
    - name: build
      run: autoreconf && ./scripts/install-hdf5.sh 2> /dev/null &&./scripts/install-hts.sh && ./configure --enable-localhdf5 && make -j8
    - name: test
      run: make test
    - name: test valgrind
      run: valgrind --leak-check=full --error-exitcode=1 ./f5c call-methylation -b test/ecoli_2kb_region/reads.sorted.bam -g test/ecoli_2kb_region/draft.fa -r test/ecoli_2kb_region/reads.fasta -t 8 -K 256 -B 2M > /dev/null
  ubuntu_16_pure_make:
    name: Ubuntu 16 pure make
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev
    - name: build
      run: make
    - name: test
      run: make test
  ubuntu_18:
    name: Ubuntu 18
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libhdf5-dev
    - name: build
      run: autoreconf && ./scripts/install-hts.sh && ./configure && make -j8
    - name: test
      run: make test
  ubuntu_20:
    name: Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libhdf5-dev
    - name: build
      run: autoreconf && ./scripts/install-hts.sh && ./configure && make -j8
    - name: test
      run: make test
  ubuntu_14_cuda_6_5:
    name: Ubuntu 14 cuda 6.5
    runs-on: ubuntu-16.04
    container: ubuntu:14.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev  libhdf5-dev gcc g++ autoconf automake make wget 
    - name: env
      run: lsb_release -a &&  ldd --version && gcc --version && g++ --version
    - name: cuda repo setup
      run: wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo apt-get update
    - name: cuda install
      run: sudo apt-get install -y cuda-core-6-5 cuda-cudart-dev-6-5
    - name: cuda env setup
      run: sudo ln -s /usr/local/cuda-6.5/ /usr/local/cuda
    - name: build
      run: export PATH=/usr/local/cuda/bin:${PATH} && autoreconf && ./scripts/install-hts.sh && ./configure && make cuda=1 -j8
    - name: test
      run: scripts/test.sh --custom --disable-cuda=yes 
