name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  ubuntu_14:
    name: ubuntu_14
    runs-on: ubuntu-20.04
    container: ubuntu:14.04
    steps:
    - name: install git
      run: sudo apt-get install -y software-properties-common && sudo add-apt-repository ppa:git-core/ppa && sudo apt-get update -y && sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc g++ autoconf automake make wget
    - name: cuda install
      run: wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo apt-get update && sudo apt-get install -y cuda-core-6-5 cuda-cudart-dev-6-5 && sudo ln -s /usr/local/cuda-6.5/ /usr/local/cuda
    - name: env
      run: export PATH=/usr/local/cuda/bin:${PATH} && lsb_release -a &&  ldd --version && gcc --version && g++ --version && nvcc --version
    - name: build
      run: export PATH=/usr/local/cuda/bin:${PATH} && make release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: latest
        files: |
          *.tar.gz
