name: "Release simulation"

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  ubuntu_14:
    name: ubuntu_14
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:14.04
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: install git
      run: sudo apt-get install -y software-properties-common && sudo add-apt-repository ppa:git-core/ppa && sudo apt-get update -y && sudo apt-get install git -y
    - name: nodejs
      run: |
        apt-get install -y wget xz-utils
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc g++ autoconf automake make wget
    - name: cuda install
      run: wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb && sudo apt-get update && sudo apt-get install -y cuda-core-6-5 cuda-cudart-dev-6-5 && sudo ln -s /usr/local/cuda-6.5/ /usr/local/cuda
    - name: env
      run: export PATH=/usr/local/cuda/bin:${PATH} && lsb_release -a &&  ldd --version && gcc --version && g++ --version && nvcc --version
    - name: build
      run: export PATH=/usr/local/cuda/bin:${PATH} && make release
